const motivationalQuotes = [
  "Code is the canvas where ideas become alive.",
  "Every bug fixed is a lesson learned.",
  "Great software is built one commit at a time.",
  "In the world of code, curiosity is your superpower.",
  "The best code is the one that tells a story.",
  "Debug your doubts, compile your dreams.",
  "Innovation starts with a single line of code.",
  "Code with passion, deploy with confidence.",
  "Every expert was once a beginner who never gave up.",
  "Your code today shapes tomorrow's possibilities.",
  "Simplicity is the ultimate sophistication in coding.",
  "Think twice, code once.",
  "The keyboard is mightier than the sword.",
  "Transform coffee into code, and code into magic.",
  "Learning to code is learning to create.",
  "Embrace the errors, they are your greatest teachers.",
  "Code is poetry written for machines to dance.",
  "Build something that matters, one function at a time.",
  "The only way to do great work is to love what you code.",
  "Stay hungry, stay foolish, keep coding.",
  "Your potential is limitless, just like an infinite loop.",
  "Dream in code, wake up and build.",
  "Every masterpiece starts with a blank editor.",
  "Code like nobody's watching, ship like everybody is.",
  "The future belongs to those who code it.",
];

export default motivationalQuotes;
